//
// A double-double class.
// Copyright © 2022 Warren Weckesser
// Copyright © 2026 Björn Dahlgren
//
// MIT license:
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the “Software”), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED “AS IS”, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
// FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.
//
// This is an incomplete translation and extension of the Python code
// "doubledouble.py" by Juraj Sukop (https://github.com/sukop/doubledouble).
// That file has the following license and copyright notice:
// # Copyright (c) 2017, Juraj Sukop
// #
// # Permission to use, copy, modify, and/or distribute this software for any
// # purpose with or without fee is hereby granted, provided that the above
// # copyright notice and this permission notice appear in all copies.
// #
// # THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES WITH
// # REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY
// # AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY SPECIAL, DIRECT,
// # INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM
// # LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE
// # OR OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
// # PERFORMANCE OF THIS SOFTWARE.
//
// The implementation of expm1() is derived from the quadruple precision
// implementation of expm1() in the Boost math library.  The Boost license is
//
// # Boost Software License - Version 1.0 - August 17th, 2003
// #
// # Permission is hereby granted, free of charge, to any person or organization
// # obtaining a copy of the software and accompanying documentation covered by
// # this license (the "Software") to use, reproduce, display, distribute,
// # execute, and transmit the Software, and to prepare derivative works of the
// # Software, and to permit third-parties to whom the Software is furnished to
// # do so, all subject to the following:
// #
// # The copyright notices in the Software and this entire statement, including
// # the above license grant, this restriction and the following disclaimer,
// # must be included in all copies of the Software, in whole or in part, and
// # all derivative works of the Software, unless such copies or derivative
// # works are solely in the form of machine-executable object code generated by
// # a source language processor.
// #
// # THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// # IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// # FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
// # SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
// # FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
// # ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// # DEALINGS IN THE SOFTWARE.
//


#ifndef DOUBLEDOUBLE_H
#define DOUBLEDOUBLE_H

#include <cassert>
#include <cstdio>
#include <cstdlib>
#include <cmath>
#include <cfenv>
#include <cfloat>
#include <cstdint>
#include <array>
#include <vector>

namespace doubledouble {

#if __cplusplus >= 202302L  // C++23
using std::isinf;
using std::isnan;
#else
constexpr inline bool isnan(double x) noexcept // clang-21 std::isnan is not constexpr?
{
    //return x != x;  // IEEE-754 NaN is the only value that satisfies this
    return __builtin_isnan(x);
}

constexpr inline bool isinf(double x) noexcept
{
  return __builtin_isinf(x);
}
#endif

class DoubleDouble
{
public:

    double upper{0.0};
    double lower{0.0};

    constexpr
    DoubleDouble() {}

    constexpr
    DoubleDouble(double x, double y)
    {
        if (isnan(x) || isnan(y)) {
            upper = NAN;
            lower = NAN;
            return;
        }
        // XXX This canonicalization convention for INFs is experimental
        //     and subject to change.
        bool xinf = isinf(x);
        bool yinf = isinf(y);
        if (xinf && yinf) {
            if (x != y) {
                // x and y are INFs with opposite signs.  Since the numerical
                // value of the DoubleDouble is x + y, we set upper and lower
                // to NAN.
                upper = NAN;
                lower = NAN;
            }
            else {
                upper = x;
                lower = 0.0;
            }
        }
        else if (xinf) {
            upper = x;
            lower = 0.0;
        }
        else if (yinf) {
            upper = y;
            lower = 0.0;
        }
        else {
            // This is equivalent to two_sum(x, y)
            double r = x + y;
            double t = r - x;
            double e = (x - (r - t)) + (y - t);
            upper = r;
            lower = e;
        }
    }

    constexpr
    DoubleDouble(double upper) : upper(upper)
    {
        if (isnan(upper)) {
            lower = NAN;
        }
    }

    explicit operator double() const noexcept { return upper; }
    explicit operator int() const noexcept { return static_cast<int>(upper); }

    DoubleDouble operator-() const;
    DoubleDouble operator+(double x) const;
    DoubleDouble operator+(const DoubleDouble& x) const;
    DoubleDouble operator-(double x) const;
    DoubleDouble operator-(const DoubleDouble& x) const;
    DoubleDouble operator*(double x) const;
    DoubleDouble operator*(const DoubleDouble& x) const;
    DoubleDouble operator/(double x) const;
    DoubleDouble operator/(const DoubleDouble& x) const;

    DoubleDouble& operator+=(double x);
    DoubleDouble& operator+=(const DoubleDouble& x);
    DoubleDouble& operator-=(double x);
    DoubleDouble& operator-=(const DoubleDouble& x);
    DoubleDouble& operator*=(double x);
    DoubleDouble& operator*=(const DoubleDouble& x);
    DoubleDouble& operator/=(double x);
    DoubleDouble& operator/=(const DoubleDouble& x);

    bool operator==(const DoubleDouble& x) const;
    bool operator==(double x) const;
    bool operator!=(const DoubleDouble& x) const;
    bool operator!=(double x) const;
    bool operator<(double x) const;
    bool operator<(const DoubleDouble& x) const;
    bool operator<=(double x) const;
    bool operator<=(const DoubleDouble& x) const;
    bool operator>(double x) const;
    bool operator>(const DoubleDouble& x) const;
    bool operator>=(double x) const;
    bool operator>=(const DoubleDouble& x) const;

    DoubleDouble powi(int n) const;
    DoubleDouble exp() const;
    DoubleDouble expm1() const;
    DoubleDouble log() const;
    DoubleDouble log1p() const;
    DoubleDouble sqrt() const;
    DoubleDouble abs() const;
    DoubleDouble sin() const;
    DoubleDouble cos() const;
    DoubleDouble cosm1() const;
    DoubleDouble tan() const;
    DoubleDouble asin() const;
    DoubleDouble acos() const;
    DoubleDouble atan() const;
    DoubleDouble sinh() const;
    DoubleDouble cosh() const;
    DoubleDouble tanh() const;
    DoubleDouble asinh() const;
    DoubleDouble acosh() const;
    DoubleDouble atanh() const;
};

//
// Assorted predefined constants.
//

// 0
inline const DoubleDouble dd_zero{0.0, 0.0};
// 1
inline const DoubleDouble dd_one{1.0, 0.0};
// sqrt(2)
inline const DoubleDouble dd_sqrt2{1.4142135623730951, -9.667293313452913e-17};
// sqrt(1/2)
inline const DoubleDouble dd_sqrt1_2{0.7071067811865476, -4.833646656726457e-17};
// e
inline const DoubleDouble dd_e{2.7182818284590452, 1.44564689172925013472e-16};
// ln(2)
inline const DoubleDouble dd_ln2{0.6931471805599453, 2.3190468138462996e-17};
// pi
inline const DoubleDouble dd_pi{3.1415926535897932, 1.22464679914735317636e-16};
// pi/2
inline const DoubleDouble dd_pi_2{1.5707963267948966, 6.123233995736766e-17};
// 2*pi
inline const DoubleDouble dd_2pi{6.2831853071795862, 2.4492935982947064e-16};
// pi/4
inline const DoubleDouble dd_pi_4{0.7853981633974483, 3.0616169978683830e-17};
// 3*pi/4
inline const DoubleDouble dd_3pi_4{2.3561944901923448, 9.1848509936051484e-17};
// pi/24
inline const DoubleDouble dd_pi_24{0.13089969389957473, -1.3401022080638637e-17};
// 1/pi
inline const DoubleDouble dd_1_pi{0.3183098861837907, -1.9678676675182486e-17};
// 1/sqrt(pi)
inline const DoubleDouble dd_1_sqrtpi{0.5641895835477563,7.66772980658294e-18};
// 2/sqrt(pi)
inline const DoubleDouble dd_2_sqrtpi{1.1283791670955126, 1.533545961316588e-17};
// sqrt(pi/2)
inline const DoubleDouble dd_sqrt_pi_2{1.2533141373155003, -9.164289990229583e-17};
// sqrt(2/pi)
inline const DoubleDouble dd_sqrt_2_pi{0.7978845608028654, -4.98465440455546e-17};
// inf
inline const DoubleDouble dd_inf{INFINITY, 0.0};


inline DoubleDouble two_sum_quick(double x, double y)
{
    double r = x + y;
    double e = y - (r - x);
    return DoubleDouble(r, e);
}


inline DoubleDouble two_sum(double x, double y)
{
    double r = x + y;
    double t = r - x;
    double e = (x - (r - t)) + (y - t);
    return DoubleDouble(r, e);
}


inline DoubleDouble two_difference(double x, double y)
{
    double r = x - y;
    double t = r - x;
    double e = (x - (r - t)) - (y + t);
    return DoubleDouble(r, e);
}


inline DoubleDouble two_product(double x, double y)
{
    double r = x*y;
    double e = fma(x, y, -r);
    return DoubleDouble(r, e);
}


inline DoubleDouble DoubleDouble::operator-() const
{
    return DoubleDouble(-upper, -lower);
}

inline DoubleDouble DoubleDouble::operator+(double x) const
{
    DoubleDouble re = two_sum(upper, x);
    re.lower += lower;
    return two_sum_quick(re.upper, re.lower);
}

inline DoubleDouble operator+(double x, const DoubleDouble& y)
{
    return y + x;
}

inline DoubleDouble DoubleDouble::operator+(const DoubleDouble& x) const
{
    DoubleDouble re = two_sum(upper, x.upper);
    re.lower += lower + x.lower;
    return two_sum_quick(re.upper, re.lower);
}

inline DoubleDouble DoubleDouble::operator-(double x) const
{
    DoubleDouble re = two_difference(upper, x);
    re.lower += lower;
    return two_sum_quick(re.upper, re.lower);
}

inline DoubleDouble operator-(double x, const DoubleDouble& y)
{
    return -y + x;
}

inline DoubleDouble DoubleDouble::operator-(const DoubleDouble& x) const
{
    DoubleDouble re = two_difference(upper, x.upper);
    re.lower += lower - x.lower;
    return two_sum_quick(re.upper, re.lower);
}

inline DoubleDouble DoubleDouble::operator*(double x) const
{
    DoubleDouble re = two_product(upper, x);
    re.lower += lower * x;
    return two_sum_quick(re.upper, re.lower);
}

inline DoubleDouble operator*(double x, const DoubleDouble& y)
{
    return y * x;
}

inline DoubleDouble DoubleDouble::operator*(const DoubleDouble& x) const
{
    DoubleDouble re = two_product(upper, x.upper);
    re.lower += upper*x.lower + lower*x.upper;
    return two_sum_quick(re.upper, re.lower);
}

inline DoubleDouble DoubleDouble::operator/(double x) const
{
    double r = upper/x;
    DoubleDouble sf = two_product(r, x);
    double e = (upper - sf.upper - sf.lower + lower)/x;
    return two_sum_quick(r, e);
}

inline DoubleDouble operator/(double x, const DoubleDouble& y)
{
    return DoubleDouble(x) / y;
}

inline DoubleDouble DoubleDouble::operator/(const DoubleDouble& x) const
{
    double r = upper/x.upper;
    DoubleDouble sf = two_product(r, x.upper);
    double e = (upper - sf.upper - sf.lower + lower - r*x.lower)/x.upper;
    return two_sum_quick(r, e);
}

inline DoubleDouble& DoubleDouble::operator+=(double x)
{
    DoubleDouble re = two_sum(upper, x);
    re.lower += lower;
    *this = two_sum_quick(re.upper, re.lower);
    return *this;
}

inline DoubleDouble& DoubleDouble::operator+=(const DoubleDouble& x)
{
    DoubleDouble re = two_sum(upper, x.upper);
    re.lower += lower + x.lower;
    *this = two_sum_quick(re.upper, re.lower);
    return *this;
}

inline DoubleDouble& DoubleDouble::operator-=(double x)
{
    DoubleDouble re = two_difference(upper, x);
    re.lower += lower;
    *this = two_sum_quick(re.upper, re.lower);
    return *this;
}

inline DoubleDouble& DoubleDouble::operator-=(const DoubleDouble& x)
{
    DoubleDouble re = two_difference(upper, x.upper);
    re.lower += lower - x.lower;
    *this = two_sum_quick(re.upper, re.lower);
    return *this;
}

inline DoubleDouble& DoubleDouble::operator*=(double x)
{
    DoubleDouble re = two_product(upper, x);
    re.lower += lower * x;
    *this = two_sum_quick(re.upper, re.lower);
    return *this;
}

inline DoubleDouble& DoubleDouble::operator*=(const DoubleDouble& x)
{
    DoubleDouble re = two_product(upper, x.upper);
    re.lower += upper*x.lower + lower*x.upper;
    *this = two_sum_quick(re.upper, re.lower);
    return *this;
}

inline DoubleDouble& DoubleDouble::operator/=(double x)
{
    double r = upper/x;
    DoubleDouble sf = two_product(r, x);
    double e = (upper - sf.upper - sf.lower + lower)/x;
    *this = two_sum_quick(r, e);
    return *this;
}

inline DoubleDouble& DoubleDouble::operator/=(const DoubleDouble& x)
{
    double r = upper/x.upper;
    DoubleDouble sf = two_product(r, x.upper);
    double e = (upper - sf.upper - sf.lower + lower - r*x.lower)/x.upper;
    *this = two_sum_quick(r, e);
    return *this;
}

inline bool DoubleDouble::operator==(const DoubleDouble& x) const
{
    // XXX Do the (upper, lower) representations need to be canonicalized first?
    return (upper == x.upper) && (lower == x.lower);
}

inline bool DoubleDouble::operator==(double x) const
{
    // XXX Do the (upper, lower) representations need to be canonicalized first?
    return (upper == x) && (lower == 0.0);
}

inline bool operator==(double x, const DoubleDouble& y)
{
    return y == x;
}

inline bool DoubleDouble::operator!=(const DoubleDouble& x) const
{
    // XXX Do the (upper, lower) representations need to be canonicalized first?
    return (upper != x.upper) || (lower != x.lower);
}

inline bool DoubleDouble::operator!=(double x) const
{
    // XXX Do the (upper, lower) representations need to be canonicalized first?
    return (upper != x) || (lower != 0.0);
}

inline bool operator!=(double x, const DoubleDouble& y)
{
    return y != x;
}

inline bool DoubleDouble::operator<(const DoubleDouble& x) const
{
    // XXX Do the (upper, lower) representations need to be canonicalized first?
    return (upper < x.upper) || ((upper == x.upper) && (lower < x.lower));
}

inline bool DoubleDouble::operator<(double x) const
{
    // XXX Do the (upper, lower) representations need to be canonicalized first?
    return (upper < x) || ((upper == x) && (lower < 0.0));
}

inline bool operator<(double x, const DoubleDouble& y)
{
    return y >= x;
}

inline bool DoubleDouble::operator<=(const DoubleDouble& x) const
{
    // XXX Do the (upper, lower) representations need to be canonicalized first?
    return (upper < x.upper) || ((upper == x.upper) && (lower <= x.lower));
}

inline bool DoubleDouble::operator<=(double x) const
{
    // XXX Do the (upper, lower) representations need to be canonicalized first?
    return (upper < x) || ((upper == x) && (lower <= 0.0));
}

inline bool operator<=(double x, const DoubleDouble& y)
{
    return y >= x;
}

inline bool DoubleDouble::operator>(const DoubleDouble& x) const
{
    // XXX Do the (upper, lower) representations need to be canonicalized first?
    return (upper > x.upper) || ((upper == x.upper) && (lower > x.lower));
}

inline bool DoubleDouble::operator>(double x) const
{
    // XXX Do the (upper, lower) representations need to be canonicalized first?
    return (upper > x) || ((upper == x) && (lower > 0.0));
}

inline bool operator>(double x, const DoubleDouble& y)
{
    return y <= x;
}

inline bool DoubleDouble::operator>=(const DoubleDouble& x) const
{
    // XXX Do the (upper, lower) representations need to be canonicalized first?
    return (upper > x.upper) || ((upper == x.upper) && (lower >= x.lower));
}

inline bool DoubleDouble::operator>=(double x) const
{
    // XXX Do the (upper, lower) representations need to be canonicalized first?
    return (upper > x) || ((upper == x) && (lower >= 0.0));
}

inline bool operator>=(double x, const DoubleDouble& y)
{
    return y <= x;
}

inline DoubleDouble DoubleDouble::powi(int n) const
{
    int i = std::abs(n);
    DoubleDouble b = *this;
    DoubleDouble r(1);
    while (1) {
        if ((i & 1) == 1) {
            r = r * b;
        }
        if (i <= 1) {
            break;
        }
        i >>= 1;
        b = b*b;
    }
    if (n < 0) {
        return dd_one / r;
    }
    return r;
}


inline DoubleDouble DoubleDouble::exp() const
{
    if (upper > 709.782712893384) {
        return dd_inf;
    }
    if (upper < -745.1332191019411) {
        // -745: smallest denormal
        return dd_zero;
    }
    int n = int(round(upper));
    DoubleDouble x(upper - n, lower);
    DoubleDouble u = (((((((((((x +
                     156)*x + 12012)*x +
                     600600)*x + 21621600)*x +
                     588107520)*x + 12350257920)*x +
                     201132771840)*x + 2514159648000)*x +
                     23465490048000)*x + 154872234316800)*x +
                     647647525324800)*x + 1295295050649600;
    DoubleDouble v = (((((((((((x -
                     156)*x + 12012)*x -
                     600600)*x + 21621600)*x -
                     588107520)*x + 12350257920)*x -
                     201132771840)*x + 2514159648000)*x -
                     23465490048000)*x + 154872234316800)*x -
                     647647525324800)*x + 1295295050649600;
    // printf("\nexp_arg=%23.17e,%23.17E\n", this->upper, this->lower);
    DoubleDouble result = dd_e.powi(n) * (u / v);
    // printf("\nexp_res=%23.17e,%23.17E\n", result.upper, result.lower);
    return result;
}

inline DoubleDouble DoubleDouble::sqrt() const
{
    if (upper == 0 && lower == 0) {
        return dd_zero;
    }
    double r = std::sqrt(upper);
    DoubleDouble sf = two_product(r, r);
    double e = (upper - sf.upper - sf.lower + lower) * 0.5 / r;
    return two_sum_quick(r, e);
}

// XXX See the various relative tolerances in the unit tests
// for cases where it would be nice to get a more accurate
// result.
inline DoubleDouble DoubleDouble::log() const
{
    //printf("\nla=%23.17e,%23.17E\n", this->upper, this->lower);
    DoubleDouble r(std::log(upper));
    DoubleDouble u = r.exp();
    //printf("r0=%23.17e,%23.17E\n", r.upper, r.lower);
    r = r - DoubleDouble(2.0)*(u - *this)/(u + *this);
    //printf("r1=%23.17e,%23.17E\n", r.upper, r.lower);

    return r;
}

inline DoubleDouble DoubleDouble::log1p() const
{
    if ((*this).abs() < 1e-5) {
        // Taylor polynomial:
        return (*this)*(1.0 + (*this)*(-0.5 + (*this)*(1.0/DoubleDouble(3.0) + (*this)*(-0.25 + (*this)*(1.0/DoubleDouble(5.0) - (*this)/6.0)))));
    }
    if ((*this).abs() < 0.5) {
        DoubleDouble guess = std::log1p(this->upper);
        // log(x+1) = y
        // x + 1 = exp(y)
        // x = exp(y) - 1
        // f(y) = exp(y) - 1 - x, find y so that f(y) == 0 (using newton's method)
        // f'(y) = exp(y)
        // delta_y := -f(y)/f'(y) = (x - expm1(y)/exp(y) ; <-- single Newton step
        // Quadratic convergence of newton's method means that correct mantissa bits
        // are doubled each iteration, hence a single iteration should be enough here.
        DoubleDouble em1 = guess.expm1();
        guess += ((*this) - em1) / (1 + em1);
        return guess;
    }
    DoubleDouble xp1 = (*this) + 1.0;
    return xp1.log();
}

inline DoubleDouble DoubleDouble::abs() const
{
    if (*this < 0.0) {
        return -*this;
    }
    else {
        return *this;
    }
}

inline bool is_zero(DoubleDouble const& x)
{
    return x.upper == 0.0 && x.lower == 0.0;
}

inline bool signbit(DoubleDouble const& x)
{
    return std::signbit(x.upper) || ((x.upper == 0.0) && std::signbit(x.lower));
}

inline DoubleDouble copysign(DoubleDouble const& x, DoubleDouble const& y)
{
    return signbit(x) == signbit(y) ? x : -x;
}

// Defined further down (next to the other generic-code helpers); forward-declared here
// so the trig/hyperbolic functions below can use it.
inline bool isnan(DoubleDouble const& arg);

inline DoubleDouble dd_nan()
{
    return DoubleDouble(NAN, NAN);
}

inline DoubleDouble hypot(const DoubleDouble& x, const DoubleDouble& y);

inline constexpr std::array<DoubleDouble, 6> sin_table_pi_24{{
    DoubleDouble( 1.30526192220051601e-01, -9.60766602390152377e-18),
    DoubleDouble( 2.58819045102520739e-01,  2.28724950049556087e-17),
    DoubleDouble( 3.82683432365089782e-01, -1.00507726964615876e-17),
    DoubleDouble( 5.00000000000000000e-01,  0.00000000000000000e+00),
    DoubleDouble( 6.08761429008720656e-01, -1.64704797902508702e-17),
    DoubleDouble( 7.07106781186547573e-01, -4.83364665672645673e-17),
}};

inline constexpr std::array<DoubleDouble, 6> cos_table_pi_24{{
    DoubleDouble( 9.91444861373810382e-01,  2.89898987445453692e-17),
    DoubleDouble( 9.65925826289068312e-01, -2.54639715623089554e-17),
    DoubleDouble( 9.23879532511286738e-01,  1.76450470843366771e-17),
    DoubleDouble( 8.66025403784438597e-01,  5.01754211090345140e-17),
    DoubleDouble( 7.93353340291235165e-01, -5.02862507390712490e-19),
    DoubleDouble( 7.07106781186547573e-01, -4.83364665672645673e-17),
}};

inline constexpr std::array<DoubleDouble, 8> sin_inv_fact{{
    DoubleDouble(1.66666666666666657e-01,  9.25185853854297066e-18),
    DoubleDouble(8.33333333333333322e-03,  1.15648231731787138e-19),
    DoubleDouble(1.98412698412698413e-04,  1.72095582934207053e-22),
    DoubleDouble(2.75573192239858925e-06, -1.85839327404647208e-22),
    DoubleDouble(2.50521083854417202e-08, -1.44881407093591197e-24),
    DoubleDouble(1.60590438368216133e-10,  1.25852945887520981e-26),
    DoubleDouble(7.64716373181981641e-13,  7.03872877733453001e-30),
    DoubleDouble(2.81145725434552060e-15,  1.65088427308614326e-31),
}};

inline constexpr std::array<DoubleDouble, 9> cos_inv_fact{{
    DoubleDouble(5.00000000000000000e-01,  0.00000000000000000e+00),
    DoubleDouble(4.16666666666666644e-02,  2.31296463463574266e-18),
    DoubleDouble(1.38888888888888894e-03, -5.30054395437357706e-20),
    DoubleDouble(2.48015873015873016e-05,  2.15119478667758816e-23),
    DoubleDouble(2.75573192239858883e-07,  2.37677146222502973e-23),
    DoubleDouble(2.08767569878681002e-09, -1.20734505911325997e-25),
    DoubleDouble(1.14707455977297245e-11,  2.06555127528307454e-28),
    DoubleDouble(4.77947733238738525e-14,  4.39920548583408126e-31),
    DoubleDouble(1.56192069685862253e-16,  1.19106796602737540e-32),
}};

inline DoubleDouble sin_taylor(DoubleDouble const& x)
{
    if (is_zero(x)) {
        return dd_zero;
    }
    const DoubleDouble x2 = x*x;
    const DoubleDouble poly =
        DoubleDouble(1.0) + x2 * (
            -sin_inv_fact[0] + x2 * (
                sin_inv_fact[1] + x2 * (
                    -sin_inv_fact[2] + x2 * (
                        sin_inv_fact[3] + x2 * (
                            -sin_inv_fact[4] + x2 * (
                                sin_inv_fact[5] + x2 * (
                                    -sin_inv_fact[6] + x2 *
                                    sin_inv_fact[7]
                                )
                            )
                        )
                    )
                )
            )
        );
    return x * poly;
}

inline DoubleDouble cos_taylor(DoubleDouble const& x)
{
    if (is_zero(x)) {
        return dd_one;
    }
    const DoubleDouble x2 = x*x;
    return DoubleDouble(1.0) + x2 * (
        -cos_inv_fact[0] + x2 * (
            cos_inv_fact[1] + x2 * (
                -cos_inv_fact[2] + x2 * (
                    cos_inv_fact[3] + x2 * (
                        -cos_inv_fact[4] + x2 * (
                            cos_inv_fact[5] + x2 * (
                                -cos_inv_fact[6] + x2 * (
                                    cos_inv_fact[7] + x2 *
                                    -cos_inv_fact[8]
                                )
                            )
                        )
                    )
                )
            )
        )
    );
}

inline DoubleDouble cosm1_taylor(DoubleDouble const& x)
{
    if (is_zero(x)) {
        return dd_zero;
    }
    const DoubleDouble x2 = x*x;
    return x2 * (
        -cos_inv_fact[0] + x2 * (
            cos_inv_fact[1] + x2 * (
                -cos_inv_fact[2] + x2 * (
                    cos_inv_fact[3] + x2 * (
                        -cos_inv_fact[4] + x2 * (
                            cos_inv_fact[5] + x2 * (
                                -cos_inv_fact[6] + x2 * (
                                    cos_inv_fact[7] + x2 *
                                    -cos_inv_fact[8]
                                )
                            )
                        )
                    )
                )
            )
        )
    );
}

inline void sincos_taylor(DoubleDouble const& x, DoubleDouble& s, DoubleDouble& c)
{
    s = sin_taylor(x);
    c = cos_taylor(x);
}

// 2/pi as base-2^24 digits: 2/pi = sum_i two_over_pi_24[i] * 2^(-24*(i+1)).
// Enough digits to reduce any finite double-double (max exponent ~1024) to full
// double-double precision (Payne-Hanek).
inline constexpr int32_t two_over_pi_24[] = {
    0xA2F983, 0x6E4E44, 0x1529FC, 0x2757D1, 0xF534DD, 0xC0DB62, 0x95993C, 0x439041,
    0xFE5163, 0xABDEBB, 0xC561B7, 0x246E3A, 0x424DD2, 0xE00649, 0x2EEA09, 0xD1921C,
    0xFE1DEB, 0x1CB129, 0xA73EE8, 0x8235F5, 0x2EBB44, 0x84E99C, 0x7026B4, 0x5F7E41,
    0x3991D6, 0x398353, 0x39F49C, 0x845F8B, 0xBDF928, 0x3B1FF8, 0x97FFDE, 0x05980F,
    0xEF2F11, 0x8B5A0A, 0x6D1F6D, 0x367ECF, 0x27CB09, 0xB74F46, 0x3F669E, 0x5FEA2D,
    0x7527BA, 0xC7EBE5, 0xF17B3D, 0x0739F7, 0x8A5292, 0xEA6BFB, 0x5FB11F, 0x8D5D08,
    0x560330, 0x46FC7B, 0x6BABF0, 0xCFBC20, 0x9AF436, 0x1DA9E3, 0x91615E, 0xE61B08,
    0x659985, 0x5F14A0, 0x68408D, 0xFFD880, 0x4D7327, 0x310606, 0x1556CA, 0x73A8C9,
    0x60E27B, 0xC08C6B,
};

// Payne-Hanek reduction of a (assumed finite, nonzero) modulo pi/2.
// Sets q in {0,1,2,3} and w in [-pi/4, pi/4] such that a == q*(pi/2) + w (mod 2*pi).
// Accurate to full double-double precision for all finite |a| (verified vs mpmath
// from O(1) up to 1e300). The product a*(2/pi) is formed in 24-bit integer pieces and
// accumulated modulo 8 in double-double, so no precision is lost to the huge integer part.
inline void payne_hanek_pi2(DoubleDouble const& a, int& q, DoubleDouble& w)
{
    const DoubleDouble aa = a.abs();
    const int n_digits = static_cast<int>(sizeof(two_over_pi_24)/sizeof(two_over_pi_24[0]));

    // acc accumulates (|a| * 2/pi) mod 8, kept small so no fraction bits are lost.
    // |a| = aa.upper + aa.lower exactly, so we reduce each component separately and add.
    // Each component is a single double, which splits exactly into three 24-bit pieces.
    DoubleDouble acc = dd_zero;
    const double comps[2] = {aa.upper, aa.lower};
    for (const double x : comps) {
        if (x == 0.0) {
            continue;
        }
        const int ex = std::ilogb(x) - 23;
        double z = std::scalbn(x, -ex);   // |z| in [2^23, 2^24)
        double cx[3];
        for (int c = 0; c < 3; c++) {     // value of x = sum_c cx[c]*2^(ex-24*c), exact
            const double t = static_cast<double>(static_cast<int>(z));
            cx[c] = t;
            z = (z - t) * 16777216.0;     // *2^24, exact
        }
        for (int c = 0; c < 3; c++) {
            if (cx[c] == 0.0) {
                continue;
            }
            for (int jj = 0; jj < n_digits; jj++) {
                const int e = ex - 24*(c + jj + 1);
                if (e > 2) {
                    continue;   // pure multiple of 8, irrelevant mod 8
                }
                if (e < -150) {
                    break; // below double-double precision
                }
                const double p = cx[c] * static_cast<double>(two_over_pi_24[jj]); // |p| <= 2^48, exact
                const double term = std::fmod(std::scalbn(p, e), 8.0);            // exact, in (-8, 8)
                acc = acc + DoubleDouble(term);
                if (std::fabs(acc.upper) >= 8.0) {
                    acc = acc - 8.0*std::floor(acc.upper/8.0);
                }
            }
        }
    }
    acc = acc - 8.0*std::floor(acc.upper/8.0);   // bring into [0, 8)

    const double n = std::floor(acc.upper + 0.5);
    w = (acc - n) * dd_pi_2;   // (acc - n) in [-1/2, 1/2]
    int nn = static_cast<int>(n);
    if (signbit(a)) {
        nn = -nn;
        w = -w;
    }
    q = ((nn % 4) + 4) % 4;
}

// Reduce `a` (finite, nonzero) to t + j*(pi/2) + k*(pi/24) with t in [-pi/48, pi/48],
// j in [-2, 2], k in [-6, 6] (all handled by sincos_reduced). Always succeeds (returns
// true); the bool is kept for call-site compatibility.
inline bool trig_range_reduce(DoubleDouble const& a, int& j, int& k, DoubleDouble& t)
{
    DoubleDouble w;
    if (std::fabs(a.upper) <= dd_pi_4.upper) {
        // Already in [-pi/4, pi/4]: no quadrant reduction needed.
        j = 0;
        w = a;
    }
    else if (std::fabs(a.upper) < dd_2pi.upper) {
        // |a| < 2*pi: direct reduction. z is in {0, +-1}, so dd_2pi*z is exact and
        // r = a - dd_2pi*z is an exact subtraction; the reduced angle keeps full
        // *relative* precision (important e.g. for tan just below pi/2). Payne-Hanek
        // would only give full *absolute* precision here.
        const double z = std::floor(a.upper / dd_2pi.upper + 0.5);
        const DoubleDouble r = a - dd_2pi*z;
        j = static_cast<int>(std::floor(r.upper / dd_pi_2.upper + 0.5)); // j in {-2,..,2}
        w = r - dd_pi_2*static_cast<double>(j);
    }
    else {
        // Large |a|: Payne-Hanek, full absolute double-double precision at any magnitude.
        int q;
        payne_hanek_pi2(a, q, w);
        j = (q == 3) ? -1 : q;   // q in {0,1,2,3} -> j in {0,1,2,-1}
    }
    k = static_cast<int>(std::floor(w.upper / dd_pi_24.upper + 0.5));
    t = w - dd_pi_24*static_cast<double>(k);
    return true;
}

inline void sincos_reduced(int j, int k, DoubleDouble const& t, DoubleDouble& s, DoubleDouble& c)
{
    DoubleDouble sin_t, cos_t;
    sincos_taylor(t, sin_t, cos_t);

    DoubleDouble sr = sin_t;
    DoubleDouble cr = cos_t;
    if (k != 0) {
        const int table_index = std::abs(k) - 1;
        const DoubleDouble& sk = sin_table_pi_24[table_index];
        const DoubleDouble& ck = cos_table_pi_24[table_index];
        if (k > 0) {
            sr = ck*sin_t + sk*cos_t;
            cr = ck*cos_t - sk*sin_t;
        }
        else {
            sr = ck*sin_t - sk*cos_t;
            cr = ck*cos_t + sk*sin_t;
        }
    }

    switch (j) {
    case 0:
        s = sr;
        c = cr;
        break;
    case 1:
        s = cr;
        c = -sr;
        break;
    case -1:
        s = -cr;
        c = sr;
        break;
    case 2:
    case -2:
        s = -sr;
        c = -cr;
        break;
    default:
        s = dd_nan();
        c = dd_nan();
        break;
    }
}

inline void sincos(DoubleDouble const& a, DoubleDouble& s, DoubleDouble& c)
{
    if (isnan(a)) {
        s = dd_nan();
        c = dd_nan();
        return;
    }
    if (isinf(a.upper)) {
        std::feraiseexcept(FE_INVALID);
        s = dd_nan();
        c = dd_nan();
        return;
    }
    if (is_zero(a)) {
        s = a;
        c = dd_one;
        return;
    }

    int j = 0;
    int k = 0;
    DoubleDouble t;
    if (!trig_range_reduce(a, j, k, t)) {
        s = dd_nan();
        c = dd_nan();
        return;
    }
    sincos_reduced(j, k, t, s, c);
}

inline DoubleDouble DoubleDouble::sin() const
{
    DoubleDouble s, c;
    sincos(*this, s, c);
    return s;
}

inline DoubleDouble DoubleDouble::cos() const
{
    DoubleDouble s, c;
    sincos(*this, s, c);
    return c;
}

inline DoubleDouble DoubleDouble::cosm1() const
{
    if (isnan(*this)) {
        return dd_nan();
    }
    if (isinf(upper)) {
        std::feraiseexcept(FE_INVALID);
        return dd_nan();
    }
    if (is_zero(*this)) {
        return dd_zero;
    }
    if (std::fabs(upper) <= 0.5*dd_pi_24.upper) {
        return cosm1_taylor(*this);
    }

    int j = 0;
    int k = 0;
    DoubleDouble t;
    if (!trig_range_reduce(*this, j, k, t)) {
        return dd_nan();
    }
    if (j == 0 && k == 0) {
        return cosm1_taylor(t);
    }

    DoubleDouble s, c;
    sincos_reduced(j, k, t, s, c);
    return c - dd_one;
}

inline DoubleDouble DoubleDouble::tan() const
{
    DoubleDouble s, c;
    sincos(*this, s, c);
    return s/c;
}

inline DoubleDouble sin(DoubleDouble const& arg)
{
    return arg.sin();
}

inline DoubleDouble cos(DoubleDouble const& arg)
{
    return arg.cos();
}

inline DoubleDouble cosm1(DoubleDouble const& arg)
{
    return arg.cosm1();
}

inline DoubleDouble tan(DoubleDouble const& arg)
{
    return arg.tan();
}

inline DoubleDouble atan2(DoubleDouble const& y, DoubleDouble const& x)
{
    if (isnan(x) || isnan(y)) {
        return dd_nan();
    }

    if (isinf(y.upper)) {
        if (isinf(x.upper)) {
            if (y.upper > 0.0) {
                return x.upper > 0.0 ? dd_pi_4 : dd_3pi_4;
            }
            return x.upper > 0.0 ? -dd_pi_4 : -dd_3pi_4;
        }
        return y.upper > 0.0 ? dd_pi_2 : -dd_pi_2;
    }

    if (isinf(x.upper)) {
        if (x.upper > 0.0) {
            return signbit(y) ? DoubleDouble(-0.0, 0.0) : dd_zero;
        }
        return signbit(y) ? -dd_pi : dd_pi;
    }

    if (is_zero(x) && is_zero(y)) {
        std::feraiseexcept(FE_INVALID);
        return dd_nan();
    }
    if (is_zero(y)) {
        if (x > 0.0) {
            return signbit(y) ? DoubleDouble(-0.0, 0.0) : dd_zero;
        }
        return signbit(y) ? -dd_pi : dd_pi;
    }
    if (is_zero(x)) {
        return signbit(y) ? -dd_pi_2 : dd_pi_2;
    }

    const DoubleDouble r = hypot(x, y);
    const DoubleDouble xx = x/r;
    const DoubleDouble yy = y/r;
    DoubleDouble z{std::atan2(y.upper, x.upper)};
    DoubleDouble sin_z, cos_z;
    sincos(z, sin_z, cos_z);
    if (xx.abs() > yy.abs()) {
        z += (yy - sin_z)/cos_z;
    }
    else {
        z -= (xx - cos_z)/sin_z;
    }
    return z;
}

inline DoubleDouble DoubleDouble::atan() const
{
    return atan2(*this, dd_one);
}

inline DoubleDouble atan(DoubleDouble const& arg)
{
    return arg.atan();
}

inline DoubleDouble DoubleDouble::asin() const
{
    if (isnan(*this)) {
        return dd_nan();
    }
    if (this->abs() > dd_one) {
        std::feraiseexcept(FE_INVALID);
        return dd_nan();
    }
    if (*this == dd_one) {
        return dd_pi_2;
    }
    if (*this == -dd_one) {
        return -dd_pi_2;
    }
    const DoubleDouble t = (dd_one - *this) * (dd_one + *this);
    return atan2(*this, t.sqrt());
}

inline DoubleDouble DoubleDouble::acos() const
{
    if (isnan(*this)) {
        return dd_nan();
    }
    if (this->abs() > dd_one) {
        std::feraiseexcept(FE_INVALID);
        return dd_nan();
    }
    if (*this == dd_one) {
        return dd_zero;
    }
    if (*this == -dd_one) {
        return dd_pi;
    }
    const DoubleDouble t = (dd_one - *this) * (dd_one + *this);
    return atan2(t.sqrt(), *this);
}

inline DoubleDouble asin(DoubleDouble const& arg)
{
    return arg.asin();
}

inline DoubleDouble acos(DoubleDouble const& arg)
{
    return arg.acos();
}

static const std::array<DoubleDouble, 10> numer{
    DoubleDouble(-0.028127670288085938, 1.46e-37),
    DoubleDouble(0.5127815691121048, -4.248816580490825e-17),
    DoubleDouble(-0.0632631785207471, 4.733650586348708e-18),
    DoubleDouble(0.01470328560687425, -4.57569727474415e-20),
    DoubleDouble(-0.0008675686051689528, 2.340010361165805e-20),
    DoubleDouble(8.812635961829116e-05, 2.619804163788941e-21),
    DoubleDouble(-2.596308786770631e-06, -1.6196413688647164e-22),
    DoubleDouble(1.422669108780046e-07, 1.2956999470135368e-23),
    DoubleDouble(-1.5995603306536497e-09, 5.185121944095551e-26),
    DoubleDouble(4.526182006900779e-11, -1.9856249941108077e-27)
};

static const std::array<DoubleDouble, 11> denom{
    DoubleDouble(1.0),
    DoubleDouble(-0.4544126470907431, -2.2553855773661143e-17),
    DoubleDouble(0.09682713193619222, -4.961446925746919e-19),
    DoubleDouble(-0.012745248725908178, -6.0676821249478945e-19),
    DoubleDouble(0.001147361387158326, 1.3575817248483204e-20),
    DoubleDouble(-7.370416847725892e-05, 3.720369981570573e-21),
    DoubleDouble(3.4087499397791556e-06, -3.3067348191741576e-23),
    DoubleDouble(-1.1114024704296196e-07, -3.313361038199987e-24),
    DoubleDouble(2.3987051614110847e-09, 1.102474920537503e-25),
    DoubleDouble(-2.947734185911159e-11, -9.4795654767864e-28),
    DoubleDouble(1.32220659910223e-13, 6.440648413523595e-30)
};


//
// Rational approximation of expm1(x) for -1/2 < x < 1/2
//
inline DoubleDouble expm1_rational_approx(const DoubleDouble& x)
{
    const DoubleDouble Y = DoubleDouble(1.028127670288086);
    const DoubleDouble num = (((((((((numer[9]*x + numer[8])
                                              *x + numer[7])
                                              *x + numer[6])
                                              *x + numer[5])
                                              *x + numer[4])
                                              *x + numer[3])
                                              *x + numer[2])
                                              *x + numer[1])
                                              *x + numer[0]);
    const DoubleDouble den = ((((((((((denom[10]*x + denom[9])
                                               *x + denom[8])
                                               *x + denom[7])
                                               *x + denom[6])
                                               *x + denom[5])
                                               *x + denom[4])
                                               *x + denom[3])
                                               *x + denom[2])
                                               *x + denom[1])
                                               *x + denom[0]);
    // printf("\nem1a=%23.17e,%23.17E\n", x.upper, x.lower);
    DoubleDouble result = x*Y + x * num/den;
    // printf("\nem1r=%23.17e,%23.17E\n", result.upper, result.lower);
    return result;
}


//
// This is a translation of Boost's `expm1_imp` for quad precision
// for use with DoubleDouble.
//

#define LOG_MAX_VALUE 709.782712893384

inline DoubleDouble DoubleDouble::expm1() const
{
    DoubleDouble a = (*this).abs();
    if (a.upper > 0.5) {
        if (a.upper > LOG_MAX_VALUE) {
            if (this->upper > 0) {
                // XXX Set overflow, and then return...
                return dd_inf;
            }
            return DoubleDouble(-1.0);
        }
        return (*this).exp() - 1.0;
    }
    // XXX Figure out the correct bound to use here...
    // if (a.upper < DOUBLEDOUBLE_EPSILON) {
    //    return (*this);
    // }
    return expm1_rational_approx(*this);
}

//////////////////////////////////////////////////////////////////////////
// Additional functions
//////////////////////////////////////////////////////////////////////////

inline DoubleDouble hypot(const DoubleDouble& x, const DoubleDouble &y)
{
    if (isinf(x.upper) || isinf(y.upper)) {
        return dd_inf;
    }
    auto absx = x.abs();
    auto absy = y.abs();
    auto m = (absx > absy) ? absx : absy;
    if (m.upper == 0.0 && m.lower == 0.0) {
        return dd_zero;
    }
    auto u = x/m;
    auto v = y/m;
    return m*(u*u + v*v).sqrt();
}

//
// dsum() sums an array of doubles. DoubleDouble is used internally.
//

inline double dsum(size_t n, const double *x)
{
    DoubleDouble sum{0.0, 0.0};
    for (size_t i = 0; i < n; ++i) {
        sum = sum + x[i];
    }
    return sum.upper;
}

inline double dsum(const std::vector<double>& x)
{
    return dsum(x.size(), &x[0]);
}

template <std::size_t N>
inline double dsum(const std::array<double, N>& x)
{
    return dsum(x.size(), &x[0]);
}

} // namespace

namespace doubledouble { // some missing functions for writing generic code employing "using std::fabs", etc.
inline DoubleDouble fabs(DoubleDouble const& arg)
{
    return arg.abs();
}

inline DoubleDouble exp(DoubleDouble const& arg)
{
    return arg.exp();
}
inline DoubleDouble expm1(DoubleDouble const& arg)
{
    return arg.expm1();
}
inline DoubleDouble floor(DoubleDouble const& arg) {
    double upper_floor = std::floor(arg.upper);
    if (upper_floor == arg.upper) {
        return {upper_floor, std::floor(arg.lower)};
    }
    return {upper_floor, 0.0};
}
inline DoubleDouble ceil(DoubleDouble const& arg) {
    double upper_ceil = std::ceil(arg.upper);
    if (upper_ceil == arg.upper) {
        return {upper_ceil, std::ceil(arg.lower)};
    }
    return {upper_ceil, 0.0};
}
inline DoubleDouble round(DoubleDouble const& arg) {
    if (isnan(arg)) {
        return dd_nan();
    }
    if (isinf(arg.upper)) {
        return arg;
    }
    if (signbit(arg)) {
        return -round(-arg);
    }
    return floor(arg + 0.5);
}
inline bool isnan(DoubleDouble const& arg)
{
    return isnan(arg.upper) || isnan(arg.lower);
}
inline bool isfinite(DoubleDouble const& arg)
{
    return std::isfinite(arg.upper) && std::isfinite(arg.lower);
}
inline DoubleDouble sqrt(DoubleDouble const& arg) {
    return arg.sqrt();
}
inline DoubleDouble pow(DoubleDouble const &base, DoubleDouble const &expo) {
    constexpr int const threshold_powi {17};
    bool expo_negative = std::signbit(expo.upper);
    bool expo_nonzero = expo.upper != 0 || expo.lower != 0;
    bool expo_pm_infty = isinf(expo.upper);
    bool expo_finite = expo_nonzero && !expo_pm_infty;
    bool expo_integer = !expo_pm_infty && expo == floor(expo);
    bool expo_even_integer = expo_integer && (fmod(expo.upper, 2) == 0);
    bool expo_odd_integer = expo_integer && (fabs(fmod(expo.upper, 2)) == 1);
    //bool expo_is_posinf = expo_pm_infty && expo.upper > 0;
    //bool expo_is_neginf = expo_pm_infty && expo.upper < 0;
    bool base_negative = std::signbit(base.upper);
    bool base_nonzero = base.upper != 0 || base.lower != 0;
    bool base_pm_infty = isinf(base.upper);
    bool base_finite = base_nonzero && !base_pm_infty;
    DoubleDouble abs_base = fabs(base);
    bool abs_base_lt1 = abs_base < dd_one;
    bool abs_base_gt1 = abs_base > dd_one;
    if (!base_nonzero) { // base ±0
        if (expo_negative) {
            if (expo_odd_integer) {
                if (base_negative) {
                    // pow(-0, exp), where exp is a negative odd integer, returns -∞ and raises FE_DIVBYZERO.
                    std::feraiseexcept(FE_DIVBYZERO);
                    return -dd_inf;
                }  else {
                    // pow(+0, exp), where exp is a negative odd integer, returns +∞ and raises FE_DIVBYZERO.
                    std::feraiseexcept(FE_DIVBYZERO);
                    return dd_inf;
                }
            } else if (expo_finite && !expo_odd_integer) {
                // pow(±0, exp), where exp is negative, finite, and is an even integer or a non-integer, returns +∞ and raises FE_DIVBYZERO.
                std::feraiseexcept(FE_DIVBYZERO);
                return dd_inf;
            } else if (expo_pm_infty) {
                // pow(±0, -∞) returns +∞ and may raise FE_DIVBYZERO.
                std::feraiseexcept(FE_DIVBYZERO);
                return dd_inf;
            }
        } else { // expo positive
            if (expo_odd_integer) {
                if (base_negative) {
                    // pow(-0, exp), where exp is a positive odd integer, returns -0.
                    return {-0.0, -0.0};
                } else {
                    // pow(+0, exp), where exp is a positive odd integer, returns +0.
                    return dd_zero;
                }
            } else if (!expo_odd_integer) {
                // pow(±0, exp), where exp is positive non-integer or a positive even integer, returns +0.
                return dd_zero;
            }
        }
    }
    if (base == -dd_one && !expo_finite) [[unlikely]] {
        // pow(-1, ±∞) returns 1.
        return dd_one;
    }
    if (base == dd_one) {
        // pow(+1, exp) returns 1 for any exp, even when exp is NaN.
        return dd_one;
    }
    if (!expo_nonzero) {
        // pow(base, ±0) returns 1 for any base, even when base is NaN.
        return dd_one;
    }
    if (base_finite && base_negative && expo_finite && !expo_integer) {
        // pow(base, exp) returns NaN and raises FE_INVALID if base is finite and negative and exp is finite and non-integer.
        std::feraiseexcept(FE_INVALID);
        return {NAN, NAN};
    }
    if (expo.upper == -INFINITY) {
        if (abs_base_lt1) {
            // pow(base, -∞) returns +∞ for any |base| < 1.
            return dd_inf;
        } else if (abs_base_gt1) {
            // pow(base, -∞) returns +0 for any |base| > 1.
            return dd_zero;
        }
    } else if (expo.upper == INFINITY) {
        if (abs_base_lt1) {
            // pow(base, +∞) returns +0 for any |base| < 1.
            return dd_zero;
        } else if (abs_base_gt1) {
            // pow(base, +∞) returns +∞ for any |base| > 1.
            return dd_inf;
        }
    }
    if (base.upper == -INFINITY) {
        if (expo_odd_integer) {
            if (expo_negative) {
                // pow(-∞, exp) returns -0 if exp is a negative odd integer.
                return {-0.0, -0.0};
            } else {
                // pow(-∞, exp) returns -∞ if exp is a positive odd integer.
                return -dd_inf;
            }
        }
        if (expo_negative) {
            // pow(-∞, exp) returns +0 if exp is a negative non-integer or negative even integer.
            return dd_zero;
        } else {
            // pow(-∞, exp) returns +∞ if exp is a positive non-integer or positive even integer.
            return dd_inf;
        }
    } else if (base.upper == +INFINITY){
        if (expo_negative) {
            // pow(+∞, exp) returns +0 for any negative exp.
            return dd_zero;
        } else {
            // pow(+∞, exp) returns +∞ for any positive exp.
            return dd_inf;
        }
    }
    if (isnan(base) || isnan(expo)) {
        // except where specified above, if any argument is NaN, NaN is returned.
        return {NAN, NAN};
    }
    if (expo_integer and fabs(expo) < threshold_powi) {
        return base.powi((int)expo.upper);
    }
    if (base_negative && expo_integer) {
        DoubleDouble pow_mbase = ((-base).log()*expo).exp();
        if (expo_odd_integer) {
            return -pow_mbase;
        } else {
            assert(expo_even_integer);
            return pow_mbase;
        }
    }
    return (base.log()*expo).exp();
}

inline DoubleDouble log1p(DoubleDouble const& arg)
{
    return arg.log1p();
}

inline DoubleDouble log(DoubleDouble const& arg)
{
    return arg.log();
}

inline DoubleDouble scalbn(DoubleDouble const& arg, int expo) {
    return DoubleDouble(std::scalbn(arg.upper, expo), std::scalbn(arg.lower, expo));
}
inline DoubleDouble frexp(DoubleDouble const& arg, int *expo) {
    double mant = std::frexp(arg.upper, expo);
    return DoubleDouble{mant, std::scalbn(arg.lower, -*expo)};
}
inline DoubleDouble fma(DoubleDouble const& x, DoubleDouble const& y, DoubleDouble const& z) {
    // x*y + z
    // >>> ((X+x)*(Y+y) + (Z+z)).expand()
    // X⋅Y + X⋅y + Y⋅x + x⋅y + Z + z
    DoubleDouble XY = two_product(x.upper, y.upper);
    DoubleDouble Xy = two_product(x.upper, y.lower);
    DoubleDouble Yx = two_product(y.upper, x.lower);
    DoubleDouble xy = two_product(x.lower, y.lower);
    return (((XY + z) + Xy) + Yx) + xy;
}
inline void sincosh(DoubleDouble const& x, DoubleDouble& s, DoubleDouble& c)
{
    if (isnan(x)) {
        s = dd_nan();
        c = dd_nan();
        return;
    }
    if (isinf(x.upper)) {
        s = x.upper > 0 ? dd_inf : -dd_inf;
        c = dd_inf;
        return;
    }
    if (is_zero(x)) {
        s = x;
        c = dd_one;
        return;
    }
    if (signbit(x)) {
        sincosh(-x, s, c);
        s = -s;
        return;
    }
    if (x.upper > 40.0) {
        if (x.upper - dd_ln2.upper > LOG_MAX_VALUE) {
            // TODO: for consistency with exp()/pow(), raise the overflow flag here:
            // std::feraiseexcept(FE_OVERFLOW);
            s = dd_inf;
            c = dd_inf;
            return;
        }
        DoubleDouble e = (x - dd_ln2).exp();
        s = e;
        c = e;
        return;
    }
    DoubleDouble u = x.expm1();
    s = u * (u + 2.0) / (2.0 * (u + 1.0));
    c = 1.0 + (u * u) / (2.0 * (u + 1.0));
}

inline DoubleDouble DoubleDouble::sinh() const
{
    DoubleDouble s, c;
    sincosh(*this, s, c);
    return s;
}

inline DoubleDouble DoubleDouble::cosh() const
{
    DoubleDouble s, c;
    sincosh(*this, s, c);
    return c;
}

inline DoubleDouble DoubleDouble::tanh() const
{
    if (isnan(*this)) {
        return dd_nan();
    }
    if (isinf(upper)) {
        return upper > 0 ? dd_one : -dd_one;
    }
    if (is_zero(*this)) {
        return *this;
    }
    if (signbit(*this)) {
        return -(-*this).tanh();
    }
    if (upper > 40.0) {
        return dd_one;
    }
    DoubleDouble u = (2.0 * (*this)).expm1();
    return u / (u + 2.0);
}

inline DoubleDouble DoubleDouble::asinh() const
{
    if (isnan(*this)) {
        return dd_nan();
    }
    if (isinf(upper)) {
        return *this;
    }
    if (is_zero(*this)) {
        return *this;
    }
    if (signbit(*this)) {
        return -(-*this).asinh();
    }
    if (upper > 1e150) {
        return this->log() + dd_ln2;
    }
    DoubleDouble x2 = (*this) * (*this);
    DoubleDouble r = (1.0 + x2).sqrt();
    return (*this + x2 / (1.0 + r)).log1p();
}

inline DoubleDouble DoubleDouble::acosh() const
{
    if (isnan(*this)) {
        return dd_nan();
    }
    if (isinf(upper)) {
        if (upper < 0) {
            std::feraiseexcept(FE_INVALID);
            return dd_nan();
        }
        return dd_inf;
    }
    if (*this < dd_one) {
        std::feraiseexcept(FE_INVALID);
        return dd_nan();
    }
    if (*this == dd_one) {
        return dd_zero;
    }
    if (upper > 1e150) {
        return this->log() + dd_ln2;
    }
    if (upper < 1.5) {
        DoubleDouble t = *this - 1.0;
        return (t + (t * (t + 2.0)).sqrt()).log1p();
    }
    return ((*this + ((*this - 1.0) * (*this + 1.0)).sqrt()).log());
}

inline DoubleDouble DoubleDouble::atanh() const
{
    if (isnan(*this)) {
        return dd_nan();
    }
    if (is_zero(*this)) {
        return *this;
    }
    if (signbit(*this)) {
        return -(-*this).atanh();
    }
    if (*this > dd_one) {
        std::feraiseexcept(FE_INVALID);
        return dd_nan();
    }
    if (*this == dd_one) {
        std::feraiseexcept(FE_DIVBYZERO);
        return dd_inf;
    }
    return 0.5 * (2.0 * (*this) / (1.0 - *this)).log1p();
}

inline DoubleDouble sinh(DoubleDouble const& x)
{
    return x.sinh();
}

inline DoubleDouble cosh(DoubleDouble const& x)
{
    return x.cosh();
}

inline DoubleDouble tanh(DoubleDouble const& x)
{
    return x.tanh();
}

inline DoubleDouble asinh(DoubleDouble const& x)
{
    return x.asinh();
}

inline DoubleDouble acosh(DoubleDouble const& x)
{
    return x.acosh();
}

inline DoubleDouble atanh(DoubleDouble const& x)
{
    return x.atanh();
}
}
namespace std {
  template <>
  class numeric_limits<doubledouble::DoubleDouble> : public numeric_limits<double> {
  public:
      inline static double epsilon() { return 4.93038065763132e-32; /* exp2(-digits)*/ }
      inline static doubledouble::DoubleDouble infinity() { return {numeric_limits<double>::infinity(), 0}; }
      inline static doubledouble::DoubleDouble max() { return {1.797693134862315708e+308, 9.97920154767359795e+291}; }
      inline static doubledouble::DoubleDouble safe_max() { return {1.797693134862315708e+308, 9.97920154767359795e+291}; }
      inline static doubledouble::DoubleDouble quiet_NaN() { return {numeric_limits<double>::quiet_NaN(), numeric_limits<double>::quiet_NaN()}; }
      inline static double min() { return 2.0041683600089728e-292; /* exp2(-1022 + n_mantissa_bits + 1)*/ }
      static const int digits = 104;
      static const int digits10 = 31;
  };
}
#endif
