//
// A double-double class.
// Copyright © 2022 Warren Weckesser
//
// MIT license:
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the “Software”), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED “AS IS”, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
// FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.
//
// This is an incomplete translation and extension of the Python code
// "doubledouble.py" by Juraj Sukop (https://github.com/sukop/doubledouble).
// That file has the following license and copyright notice:
// # Copyright (c) 2017, Juraj Sukop
// #
// # Permission to use, copy, modify, and/or distribute this software for any
// # purpose with or without fee is hereby granted, provided that the above
// # copyright notice and this permission notice appear in all copies.
// #
// # THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES WITH
// # REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY
// # AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY SPECIAL, DIRECT,
// # INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM
// # LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE
// # OR OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
// # PERFORMANCE OF THIS SOFTWARE.
//
// The implementation of expm1() is derived from the quadruple precision
// implementation of expm1() in the Boost math library.  The Boost license is
//
// # Boost Software License - Version 1.0 - August 17th, 2003
// #
// # Permission is hereby granted, free of charge, to any person or organization
// # obtaining a copy of the software and accompanying documentation covered by
// # this license (the "Software") to use, reproduce, display, distribute,
// # execute, and transmit the Software, and to prepare derivative works of the
// # Software, and to permit third-parties to whom the Software is furnished to
// # do so, all subject to the following:
// #
// # The copyright notices in the Software and this entire statement, including
// # the above license grant, this restriction and the following disclaimer,
// # must be included in all copies of the Software, in whole or in part, and
// # all derivative works of the Software, unless such copies or derivative
// # works are solely in the form of machine-executable object code generated by
// # a source language processor.
// #
// # THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// # IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// # FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
// # SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
// # FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
// # ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// # DEALINGS IN THE SOFTWARE.
//


#ifndef DOUBLEDOUBLE_H
#define DOUBLEDOUBLE_H

#include <cstdio>
#include <cstdlib>
#include <cmath>
#include <cfloat>
#include <cstdint>
#include <array>
#include <vector>

namespace doubledouble {

class DoubleDouble
{
public:

    double upper{0.0};
    double lower{0.0};

    constexpr
    DoubleDouble() {}

    constexpr
    DoubleDouble(double x, double y)
    {
        if (std::isnan(x) || std::isnan(y)) {
            upper = NAN;
            lower = NAN;
            return;
        }
        // XXX This canonicalization convention for INFs is experimental
        //     and subject to change.
        bool xinf = std::isinf(x);
        bool yinf = std::isinf(y);
        if (xinf && yinf) {
            if (x != y) {
                // x and y are INFs with opposite signs.  Since the numerical
                // value of the DoubleDouble is x + y, we set upper and lower
                // to NAN.
                upper = NAN;
                lower = NAN;
            }
            else {
                upper = x;
                lower = 0.0;
            }
        }
        else if (xinf) {
            upper = x;
            lower = 0.0;
        }
        else if (yinf) {
            upper = y;
            lower = 0.0;
        }
        else {
            // This is equivalent to two_sum(x, y)
            double r = x + y;
            double t = r - x;
            double e = (x - (r - t)) + (y - t);
            upper = r;
            lower = e;
        }
    }

    constexpr
    DoubleDouble(double upper) : upper(upper)
    {
        if (std::isnan(upper)) {
            lower = NAN;
        }
    }

    DoubleDouble operator-() const;
    DoubleDouble operator+(double x) const;
    DoubleDouble operator+(const DoubleDouble& x) const;
    DoubleDouble operator-(double x) const;
    DoubleDouble operator-(const DoubleDouble& x) const;
    DoubleDouble operator*(double x) const;
    DoubleDouble operator*(const DoubleDouble& x) const;
    DoubleDouble operator/(double x) const;
    DoubleDouble operator/(const DoubleDouble& x) const;

    DoubleDouble& operator+=(double x);
    DoubleDouble& operator+=(const DoubleDouble& x);
    DoubleDouble& operator-=(double x);
    DoubleDouble& operator-=(const DoubleDouble& x);
    DoubleDouble& operator*=(double x);
    DoubleDouble& operator*=(const DoubleDouble& x);
    DoubleDouble& operator/=(double x);
    DoubleDouble& operator/=(const DoubleDouble& x);

    bool operator==(const DoubleDouble& x) const;
    bool operator==(double x) const;
    bool operator!=(const DoubleDouble& x) const;
    bool operator!=(double x) const;
    bool operator<(double x) const;
    bool operator<(const DoubleDouble& x) const;
    bool operator<=(double x) const;
    bool operator<=(const DoubleDouble& x) const;
    bool operator>(double x) const;
    bool operator>(const DoubleDouble& x) const;
    bool operator>=(double x) const;
    bool operator>=(const DoubleDouble& x) const;

    DoubleDouble powi(int n) const;
    DoubleDouble exp() const;
    DoubleDouble expm1() const;
    DoubleDouble log() const;
    DoubleDouble log1p() const;
    DoubleDouble sqrt() const;
    DoubleDouble abs() const;
};

//
// Assorted predefined constants.
//

// 0
inline const DoubleDouble dd_zero{0.0, 0.0};
// 1
inline const DoubleDouble dd_one{1.0, 0.0};
// sqrt(2)
inline const DoubleDouble dd_sqrt2{1.4142135623730951, -9.667293313452913e-17};
// sqrt(1/2)
inline const DoubleDouble dd_sqrt1_2{0.7071067811865476, -4.833646656726457e-17};
// e
inline const DoubleDouble dd_e{2.7182818284590452, 1.44564689172925013472e-16};
// ln(2)
inline const DoubleDouble dd_ln2{0.6931471805599453, 2.3190468138462996e-17};
// pi
inline const DoubleDouble dd_pi{3.1415926535897932, 1.22464679914735317636e-16};
// pi/2
inline const DoubleDouble dd_pi_2{1.5707963267948966, 6.123233995736766e-17};
// 1/pi
inline const DoubleDouble dd_1_pi{0.3183098861837907, -1.9678676675182486e-17};
// 1/sqrt(pi)
inline const DoubleDouble dd_1_sqrtpi{0.5641895835477563,7.66772980658294e-18};
// 2/sqrt(pi)
inline const DoubleDouble dd_2_sqrtpi{1.1283791670955126, 1.533545961316588e-17};
// sqrt(pi/2)
inline const DoubleDouble dd_sqrt_pi_2{1.2533141373155003, -9.164289990229583e-17};
// sqrt(2/pi)
inline const DoubleDouble dd_sqrt_2_pi{0.7978845608028654, -4.98465440455546e-17};
// inf
inline const DoubleDouble dd_inf{INFINITY, 0.0};


inline DoubleDouble two_sum_quick(double x, double y)
{
    double r = x + y;
    double e = y - (r - x);
    return DoubleDouble(r, e);
}


inline DoubleDouble two_sum(double x, double y)
{
    double r = x + y;
    double t = r - x;
    double e = (x - (r - t)) + (y - t);
    return DoubleDouble(r, e);
}


inline DoubleDouble two_difference(double x, double y)
{
    double r = x - y;
    double t = r - x;
    double e = (x - (r - t)) - (y + t);
    return DoubleDouble(r, e);
}


inline DoubleDouble two_product(double x, double y)
{
    double r = x*y;
    double e = fma(x, y, -r);
    return DoubleDouble(r, e);
}


inline DoubleDouble DoubleDouble::operator-() const
{
    return DoubleDouble(-upper, -lower);
}

inline DoubleDouble DoubleDouble::operator+(double x) const
{
    DoubleDouble re = two_sum(upper, x);
    re.lower += lower;
    return two_sum_quick(re.upper, re.lower);
}

inline DoubleDouble operator+(double x, const DoubleDouble& y)
{
    return y + x;
}

inline DoubleDouble DoubleDouble::operator+(const DoubleDouble& x) const
{
    DoubleDouble re = two_sum(upper, x.upper);
    re.lower += lower + x.lower;
    return two_sum_quick(re.upper, re.lower);
}

inline DoubleDouble DoubleDouble::operator-(double x) const
{
    DoubleDouble re = two_difference(upper, x);
    re.lower += lower;
    return two_sum_quick(re.upper, re.lower);
}

inline DoubleDouble operator-(double x, const DoubleDouble& y)
{
    return -y + x;
}

inline DoubleDouble DoubleDouble::operator-(const DoubleDouble& x) const
{
    DoubleDouble re = two_difference(upper, x.upper);
    re.lower += lower - x.lower;
    return two_sum_quick(re.upper, re.lower);
}

inline DoubleDouble DoubleDouble::operator*(double x) const
{
    DoubleDouble re = two_product(upper, x);
    re.lower += lower * x;
    return two_sum_quick(re.upper, re.lower);
}

inline DoubleDouble operator*(double x, const DoubleDouble& y)
{
    return y * x;
}

inline DoubleDouble DoubleDouble::operator*(const DoubleDouble& x) const
{
    DoubleDouble re = two_product(upper, x.upper);
    re.lower += upper*x.lower + lower*x.upper;
    return two_sum_quick(re.upper, re.lower);
}

inline DoubleDouble DoubleDouble::operator/(double x) const
{
    double r = upper/x;
    DoubleDouble sf = two_product(r, x);
    double e = (upper - sf.upper - sf.lower + lower)/x;
    return two_sum_quick(r, e);
}

inline DoubleDouble operator/(double x, const DoubleDouble& y)
{
    return DoubleDouble(x) / y;
}

inline DoubleDouble DoubleDouble::operator/(const DoubleDouble& x) const
{
    double r = upper/x.upper;
    DoubleDouble sf = two_product(r, x.upper);
    double e = (upper - sf.upper - sf.lower + lower - r*x.lower)/x.upper;
    return two_sum_quick(r, e);
}

inline DoubleDouble& DoubleDouble::operator+=(double x)
{
    DoubleDouble re = two_sum(upper, x);
    re.lower += lower;
    *this = two_sum_quick(re.upper, re.lower);
    return *this;
}

inline DoubleDouble& DoubleDouble::operator+=(const DoubleDouble& x)
{
    DoubleDouble re = two_sum(upper, x.upper);
    re.lower += lower + x.lower;
    *this = two_sum_quick(re.upper, re.lower);
    return *this;
}

inline DoubleDouble& DoubleDouble::operator-=(double x)
{
    DoubleDouble re = two_difference(upper, x);
    re.lower += lower;
    *this = two_sum_quick(re.upper, re.lower);
    return *this;
}

inline DoubleDouble& DoubleDouble::operator-=(const DoubleDouble& x)
{
    DoubleDouble re = two_difference(upper, x.upper);
    re.lower += lower - x.lower;
    *this = two_sum_quick(re.upper, re.lower);
    return *this;
}

inline DoubleDouble& DoubleDouble::operator*=(double x)
{
    DoubleDouble re = two_product(upper, x);
    re.lower += lower * x;
    *this = two_sum_quick(re.upper, re.lower);
    return *this;
}

inline DoubleDouble& DoubleDouble::operator*=(const DoubleDouble& x)
{
    DoubleDouble re = two_product(upper, x.upper);
    re.lower += upper*x.lower + lower*x.upper;
    *this = two_sum_quick(re.upper, re.lower);
    return *this;
}

inline DoubleDouble& DoubleDouble::operator/=(double x)
{
    double r = upper/x;
    DoubleDouble sf = two_product(r, x);
    double e = (upper - sf.upper - sf.lower + lower)/x;
    *this = two_sum_quick(r, e);
    return *this;
}

inline DoubleDouble& DoubleDouble::operator/=(const DoubleDouble& x)
{
    double r = upper/x.upper;
    DoubleDouble sf = two_product(r, x.upper);
    double e = (upper - sf.upper - sf.lower + lower - r*x.lower)/x.upper;
    *this = two_sum_quick(r, e);
    return *this;
}

inline bool DoubleDouble::operator==(const DoubleDouble& x) const
{
    // XXX Do the (upper, lower) representations need to be canonicalized first?
    return (upper == x.upper) && (lower == x.lower);
}

inline bool DoubleDouble::operator==(double x) const
{
    // XXX Do the (upper, lower) representations need to be canonicalized first?
    return (upper == x) && (lower == 0.0);
}

inline bool operator==(double x, const DoubleDouble& y)
{
    return y == x;
}

inline bool DoubleDouble::operator!=(const DoubleDouble& x) const
{
    // XXX Do the (upper, lower) representations need to be canonicalized first?
    return (upper != x.upper) || (lower != x.lower);
}

inline bool DoubleDouble::operator!=(double x) const
{
    // XXX Do the (upper, lower) representations need to be canonicalized first?
    return (upper != x) || (lower != 0.0);
}

inline bool operator!=(double x, const DoubleDouble& y)
{
    return y != x;
}

inline bool DoubleDouble::operator<(const DoubleDouble& x) const
{
    // XXX Do the (upper, lower) representations need to be canonicalized first?
    return (upper < x.upper) || ((upper == x.upper) && (lower < x.lower));
}

inline bool DoubleDouble::operator<(double x) const
{
    // XXX Do the (upper, lower) representations need to be canonicalized first?
    return (upper < x) || ((upper == x) && (lower < 0.0));
}

inline bool operator<(double x, const DoubleDouble& y)
{
    return y >= x;
}

inline bool DoubleDouble::operator<=(const DoubleDouble& x) const
{
    // XXX Do the (upper, lower) representations need to be canonicalized first?
    return (upper < x.upper) || ((upper == x.upper) && (lower <= x.lower));
}

inline bool DoubleDouble::operator<=(double x) const
{
    // XXX Do the (upper, lower) representations need to be canonicalized first?
    return (upper < x) || ((upper == x) && (lower <= 0.0));
}

inline bool operator<=(double x, const DoubleDouble& y)
{
    return y >= x;
}

inline bool DoubleDouble::operator>(const DoubleDouble& x) const
{
    // XXX Do the (upper, lower) representations need to be canonicalized first?
    return (upper > x.upper) || ((upper == x.upper) && (lower > x.lower));
}

inline bool DoubleDouble::operator>(double x) const
{
    // XXX Do the (upper, lower) representations need to be canonicalized first?
    return (upper > x) || ((upper == x) && (lower > 0.0));
}

inline bool operator>(double x, const DoubleDouble& y)
{
    return y <= x;
}

inline bool DoubleDouble::operator>=(const DoubleDouble& x) const
{
    // XXX Do the (upper, lower) representations need to be canonicalized first?
    return (upper > x.upper) || ((upper == x.upper) && (lower >= x.lower));
}

inline bool DoubleDouble::operator>=(double x) const
{
    // XXX Do the (upper, lower) representations need to be canonicalized first?
    return (upper > x) || ((upper == x) && (lower >= 0.0));
}

inline bool operator>=(double x, const DoubleDouble& y)
{
    return y <= x;
}

inline DoubleDouble DoubleDouble::powi(int n) const
{
    int i = std::abs(n);
    DoubleDouble b = *this;
    DoubleDouble r(1);
    while (1) {
        if ((i & 1) == 1) {
            r = r * b;
        }
        if (i <= 1) {
            break;
        }
        i >>= 1;
        b = b*b;
    }
    if (n < 0) {
        return dd_one / r;
    }
    return r;
}


inline DoubleDouble DoubleDouble::exp() const
{
    if (upper > 709.782712893384) {
        return dd_inf;
    }
    int n = int(round(upper));
    DoubleDouble x(upper - n, lower);
    DoubleDouble u = (((((((((((x +
                     156)*x + 12012)*x +
                     600600)*x + 21621600)*x +
                     588107520)*x + 12350257920)*x +
                     201132771840)*x + 2514159648000)*x +
                     23465490048000)*x + 154872234316800)*x +
                     647647525324800)*x + 1295295050649600;
    DoubleDouble v = (((((((((((x -
                     156)*x + 12012)*x -
                     600600)*x + 21621600)*x -
                     588107520)*x + 12350257920)*x -
                     201132771840)*x + 2514159648000)*x -
                     23465490048000)*x + 154872234316800)*x -
                     647647525324800)*x + 1295295050649600;
    // printf("\nexp_arg=%23.17e,%23.17E\n", this->upper, this->lower);
    DoubleDouble result = dd_e.powi(n) * (u / v);
    // printf("\nexp_res=%23.17e,%23.17E\n", result.upper, result.lower);
    return result;
}

inline DoubleDouble DoubleDouble::sqrt() const
{
    if (upper == 0 && lower == 0) {
        return dd_zero;
    }
    double r = std::sqrt(upper);
    DoubleDouble sf = two_product(r, r);
    double e = (upper - sf.upper - sf.lower + lower) * 0.5 / r;
    return two_sum_quick(r, e);
}

// XXX See the various relative tolerances in the unit tests
// for cases where it would be nice to get a more accurate
// result.
inline DoubleDouble DoubleDouble::log() const
{
    //printf("\nla=%23.17e,%23.17E\n", this->upper, this->lower);
    DoubleDouble r(std::log(upper));
    DoubleDouble u = r.exp();
    //printf("r0=%23.17e,%23.17E\n", r.upper, r.lower);
    r = r - DoubleDouble(2.0)*(u - *this)/(u + *this);
    //printf("r1=%23.17e,%23.17E\n", r.upper, r.lower);

    return r;
}

// inline DoubleDouble DoubleDouble::log1p() const
// {
//     DoubleDouble u = *this + 1.0;
//     if (u == 0.0) {
//         return *this;
//     }
//     return u.log()*(*this)/(u - 1.0);
// }

//
// This needs a second look.  See the various relative tolerances
// in the unit tests for cases where I think it should do better.
//
inline DoubleDouble DoubleDouble::log1p() const
{
    // if ((*this).abs() < 1e-5) {
    //     // Taylor polynomial:
    //     return (*this)*(1.0 + (*this)*(-0.5 + (*this)*(1.0/DoubleDouble(3.0) + (*this)*(-0.25 + (*this)*(1.0/DoubleDouble(5.0) - (*this)/6.0)))));
    // }
    if ((*this).abs() < 0.5) {
        DoubleDouble guess = std::log1p(this->upper);
        // log(x+1) = y
        // x + 1 = exp(y)
        // x = exp(y) - 1
        // f(y) = exp(y) - 1 - x, find y so that f(y) == 0 (using newton's method)
        // f'(y) = exp(y)
        // delta_y := -f(y)/f'(y) = (x - expm1(y)/exp(y) ; <-- single Newton step
        // Quadratic convergence of newton's method means that correct mantissa bits
        // are doubled each iteration, hence a single iteration should be enough here.
        DoubleDouble em1 = guess.expm1();
        guess += ((*this) - em1) / (1 + em1);
        return guess;
    }
    DoubleDouble xp1 = (*this) + 1.0;
    return xp1.log();
}

inline DoubleDouble DoubleDouble::abs() const
{
    if (*this < 0.0) {
        return -*this;
    }
    else {
        return *this;
    }
}

static const std::array<DoubleDouble, 10> numer{
    DoubleDouble(-0.028127670288085938, 1.46e-37),
    DoubleDouble(0.5127815691121048, -4.248816580490825e-17),
    DoubleDouble(-0.0632631785207471, 4.733650586348708e-18),
    DoubleDouble(0.01470328560687425, -4.57569727474415e-20),
    DoubleDouble(-0.0008675686051689528, 2.340010361165805e-20),
    DoubleDouble(8.812635961829116e-05, 2.619804163788941e-21),
    DoubleDouble(-2.596308786770631e-06, -1.6196413688647164e-22),
    DoubleDouble(1.422669108780046e-07, 1.2956999470135368e-23),
    DoubleDouble(-1.5995603306536497e-09, 5.185121944095551e-26),
    DoubleDouble(4.526182006900779e-11, -1.9856249941108077e-27)
};

static const std::array<DoubleDouble, 11> denom{
    DoubleDouble(1.0),
    DoubleDouble(-0.4544126470907431, -2.2553855773661143e-17),
    DoubleDouble(0.09682713193619222, -4.961446925746919e-19),
    DoubleDouble(-0.012745248725908178, -6.0676821249478945e-19),
    DoubleDouble(0.001147361387158326, 1.3575817248483204e-20),
    DoubleDouble(-7.370416847725892e-05, 3.720369981570573e-21),
    DoubleDouble(3.4087499397791556e-06, -3.3067348191741576e-23),
    DoubleDouble(-1.1114024704296196e-07, -3.313361038199987e-24),
    DoubleDouble(2.3987051614110847e-09, 1.102474920537503e-25),
    DoubleDouble(-2.947734185911159e-11, -9.4795654767864e-28),
    DoubleDouble(1.32220659910223e-13, 6.440648413523595e-30)
};


//
// Rational approximation of expm1(x) for -1/2 < x < 1/2
//
inline DoubleDouble expm1_rational_approx(const DoubleDouble& x)
{
    const DoubleDouble Y = DoubleDouble(1.028127670288086);
    const DoubleDouble num = (((((((((numer[9]*x + numer[8])
                                              *x + numer[7])
                                              *x + numer[6])
                                              *x + numer[5])
                                              *x + numer[4])
                                              *x + numer[3])
                                              *x + numer[2])
                                              *x + numer[1])
                                              *x + numer[0]);
    const DoubleDouble den = ((((((((((denom[10]*x + denom[9])
                                               *x + denom[8])
                                               *x + denom[7])
                                               *x + denom[6])
                                               *x + denom[5])
                                               *x + denom[4])
                                               *x + denom[3])
                                               *x + denom[2])
                                               *x + denom[1])
                                               *x + denom[0]);
    // printf("\nem1a=%23.17e,%23.17E\n", x.upper, x.lower);
    DoubleDouble result = x*Y + x * num/den;
    // printf("\nem1r=%23.17e,%23.17E\n", result.upper, result.lower);
    return result;
}


//
// This is a translation of Boost's `expm1_imp` for quad precision
// for use with DoubleDouble.
//

#define LOG_MAX_VALUE 709.782712893384

inline DoubleDouble DoubleDouble::expm1() const
{
    DoubleDouble a = (*this).abs();
    if (a.upper > 0.5) {
        if (a.upper > LOG_MAX_VALUE) {
            if (this->upper > 0) {
                // XXX Set overflow, and then return...
                return dd_inf;
            }
            return DoubleDouble(-1.0);
        }
        return (*this).exp() - 1.0;
    }
    // XXX Figure out the correct bound to use here...
    // if (a.upper < DOUBLEDOUBLE_EPSILON) {
    //    return (*this);
    // }
    return expm1_rational_approx(*this);
}

//////////////////////////////////////////////////////////////////////////
// Additional functions
//////////////////////////////////////////////////////////////////////////

inline DoubleDouble hypot(const DoubleDouble& x, const DoubleDouble &y)
{
    if (std::isinf(x.upper) || std::isinf(y.upper)) {
        return dd_inf;
    }
    auto absx = x.abs();
    auto absy = y.abs();
    auto m = (absx > absy) ? absx : absy;
    if (m.upper == 0.0 && m.lower == 0.0) {
        return dd_zero;
    }
    auto u = x/m;
    auto v = y/m;
    return m*(u*u + v*v).sqrt();
}

//
// dsum() sums an array of doubles. DoubleDouble is used internally.
//

inline double dsum(size_t n, const double *x)
{
    DoubleDouble sum{0.0, 0.0};
    for (size_t i = 0; i < n; ++i) {
        sum = sum + x[i];
    }
    return sum.upper;
}

inline double dsum(const std::vector<double>& x)
{
    return dsum(x.size(), &x[0]);
}

template <std::size_t N>
inline double dsum(const std::array<double, N>& x)
{
    return dsum(x.size(), &x[0]);
}

} // namespace

namespace doubledouble { // some missing functions for writing generic code employing "using std::fabs", etc.
inline DoubleDouble fabs(DoubleDouble const& arg)
{
    return arg.abs();
}

inline DoubleDouble exp(DoubleDouble const& arg)
{
    return arg.exp();
}
inline DoubleDouble expm1(DoubleDouble const& arg)
{
    return arg.expm1();
}
inline DoubleDouble floor(DoubleDouble const& arg) {
    return {std::floor(arg.upper), 0.0}; // naive implementation
}
inline DoubleDouble ceil(DoubleDouble const& arg) {
    return {std::ceil(arg.upper), 0.0}; // naive implementation
}
inline bool isnan(DoubleDouble const& arg)
{
    return std::isnan(arg.upper) || std::isnan(arg.lower);
}
inline DoubleDouble pow(DoubleDouble const &base, DoubleDouble const &expo) {
    bool expo_negative = std::signbit(expo.upper);
    bool expo_nonzero = expo.upper != 0 || expo.lower != 0;
    bool expo_pm_infty = std::isinf(expo.upper);
    bool expo_finite = expo_nonzero && !expo_pm_infty;
    bool expo_integer = expo == floor(expo);
    bool expo_even_integer =
        expo_integer && (static_cast<long long int>(expo.upper) % 2 == 0);
    bool expo_odd_integer =
        expo_integer && (static_cast<long long int>(expo.upper) % 2 == 1);
    bool expo_is_posinf = expo_pm_infty && expo.upper > 0;
    bool expo_is_neginf = expo_is_neginf && expo.upper < 0;
    bool base_negative = std::signbit(base.upper);
    bool base_nonzero = base.upper != 0 || base.lower != 0;
    bool base_pm_infty = std::isinf(base.upper);
    bool base_finite = base_nonzero && !base_pm_infty;
    DoubleDouble abs_base = fabs(base);
    bool abs_base_lt1 = abs_base < dd_one;
    bool abs_base_gt1 = abs_base > dd_one;
    if (!base_nonzero) { // base ±0
        if (expo_odd_integer) {
            if (expo_negative) {
                // pow(-0, exp), where exp is a negative odd integer, returns -∞ and raises FE_DIVBYZERO.
                std::feraiseexcept(FE_DIVBYZERO);
                return -dd_inf;
            } else {
                // pow(+0, exp), where exp is a negative odd integer, returns +∞ and raises FE_DIVBYZERO.
                std::feraiseexcept(FE_DIVBYZERO);
                return dd_inf;
            }
        }
        if (expo_negative && expo_finite && (expo_even_integer || !expo_integer)) {
            // pow(±0, exp), where exp is negative, finite, and is an even integer or a non-integer, returns +∞ and raises FE_DIVBYZERO.
            std::feraiseexcept(FE_DIVBYZERO);
            return dd_inf;
        }
        if (expo.upper == -INFINITY) {
            // pow(±0, -∞) returns +∞ and may raise FE_DIVBYZERO.
            std::feraiseexcept(FE_DIVBYZERO);
            return dd_inf;
        }
        if (!expo_negative && !expo_even_integer) {
            if (base_negative) {
                // pow(-0, exp), where exp is a positive odd integer, returns -0.
                return {-0.0, -0.0};
            } else {
                // pow(+0, exp), where exp is a positive odd integer, returns +0.
                return dd_zero;
            }
        }
        if (!expo_negative) {
            // pow(±0, exp), where exp is positive non-integer or a positive even integer, returns +0.
            return dd_zero;
        }
    }
    if (base == -dd_one && !expo_finite) [[unlikely]] {
        // pow(-1, ±∞) returns 1.
        return dd_one;
    }
    if (base == dd_one) {
        // pow(+1, exp) returns 1 for any exp, even when exp is NaN.
        return dd_one;
    }
    if (!expo_nonzero) {
        // pow(base, ±0) returns 1 for any base, even when base is NaN.
        return dd_one;
    }
    if (base_finite && base_negative && expo_finite && !expo_integer) {
        // pow(base, exp) returns NaN and raises FE_INVALID if base is finite and negative and exp is finite and non-integer.
        std::feraiseexcept(FE_INVALID);
        return {NAN, NAN};
    }
    if (expo.upper == -INFINITY) {
        if (abs_base_lt1) {
            // pow(base, -∞) returns +∞ for any |base| < 1.
            return dd_inf;
        } else if (abs_base_gt1) {
            // pow(base, -∞) returns +0 for any |base| > 1.
            return dd_zero;
        }
    } else if (expo.upper == INFINITY) {
        if (abs_base_lt1) {
            // pow(base, +∞) returns +0 for any |base| < 1.
            return dd_zero;
        } else if (abs_base_gt1) {
            // pow(base, +∞) returns +∞ for any |base| > 1.
            return dd_inf;
        }
    }
    if (base.upper == -INFINITY) {
        if (expo_odd_integer) {
            if (expo_negative) {
                // pow(-∞, exp) returns -0 if exp is a negative odd integer.
                return {-0.0, -0.0};
            } else {
                // pow(-∞, exp) returns -∞ if exp is a positive odd integer.
                return -dd_inf;
            }
        }
        if (expo_negative) {
            // pow(-∞, exp) returns +0 if exp is a negative non-integer or negative even integer.
            return dd_zero;
        } else {
            // pow(-∞, exp) returns +∞ if exp is a positive non-integer or positive even integer.
            return dd_inf;
        }
    } else if (base.upper == +INFINITY){
        if (expo_negative) {
            // pow(+∞, exp) returns +0 for any negative exp.
            return dd_zero;
        } else {
            // pow(+∞, exp) returns +∞ for any positive exp.
            return dd_inf;
        }
    }
    if (isnan(base) || isnan(expo)) {
        // except where specified above, if any argument is NaN, NaN is returned.
        return {NAN, NAN};
    }
    if (base_negative && expo_integer) {
        DoubleDouble pow_mbase = ((-base).log()*expo).exp();
        if (expo_odd_integer) {
            return -pow_mbase;
        } else {
            assert(expo_even_integer);
            return pow_mbase;
        }
    }
    return (base.log()*expo).exp();
}

inline DoubleDouble log1p(DoubleDouble const& arg)
{
    return arg.log1p();
}

inline DoubleDouble log(DoubleDouble const& arg)
{
    return arg.log();
}

inline DoubleDouble scalbn(DoubleDouble const& arg, int expo) {
    return DoubleDouble(std::scalbn(arg.upper, expo), std::scalbn(arg.lower, expo));
}
inline DoubleDouble frexp(DoubleDouble const& arg, int *expo) {
    double mant = std::frexp(arg.upper, expo);
    return DoubleDouble{mant, std::scalbn(arg.lower, -*expo)};
}
inline DoubleDouble tanh(DoubleDouble const& x) {
    // see _derivation_expm1.ipynb
    if (x < 0) {
        return -tanh(-x);
    }
    DoubleDouble absx = fabs(x);
    if (absx.upper > 0.5) {
        // TODO, implement this branch using a table lookup (of polynomial coefficients) instead?
        DoubleDouble ex = exp(x);
        DoubleDouble emx = exp(-x);
        return (ex-emx)/(ex+emx);
    }
    int expo;
    DoubleDouble m = frexp(x, &expo);
#include "doubledouble_tanh_impl.ipp"
    assert(false);
    return {0.0/0.0, 0.0/0.0};
}
}
namespace std {
  template <>
  class numeric_limits<doubledouble::DoubleDouble> : public numeric_limits<double> {
  public:
      inline static double epsilon() { return 4.93038065763132e-32; /* exp2(-digits)*/ }
      inline static doubledouble::DoubleDouble infinity() { return {numeric_limits<double>::infinity(), 0}; }
      inline static doubledouble::DoubleDouble max() { return {1.797693134862315708e+308, 9.97920154767359795e+291}; }
      inline static doubledouble::DoubleDouble safe_max() { return {1.797693134862315708e+308, 9.97920154767359795e+291}; }
      inline static doubledouble::DoubleDouble quiet_NaN() { return {numeric_limits<double>::quiet_NaN(), numeric_limits<double>::quiet_NaN()}; }
      inline static double min() { return 2.0041683600089728e-292; /* exp2(-1022 + n_mantissa_bits + 1)*/ }
      static const int digits = 104;
      static const int digits10 = 31;
  };
}
#endif
